<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# Peer Review Assignment - Data Engineer - ETL

Estimated time needed: **20** minutes

## Objectives

In this final part you will:

*   Run the ETL process
*   Extract bank and market cap data from the JSON file `bank_market_cap.json`
*   Transform the market cap currency using the exchange rate data
*   Load the transformed data into a seperate CSV

For this lab, we are going to be using Python and several Python libraries. Some of these libraries might be installed in your lab environment or in SN Labs. Others may need to be installed by you. The cells below will install these libraries when executed.

In [1]:
!pip install glob
!pip install pandas
!pip install requests
!pip install datetime

ERROR: Could not find a version that satisfies the requirement glob (from versions: none)
ERROR: No matching distribution found for glob
Requirement already satisfied: pandas in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from pandas) (1.19.2)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: requests in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from requests) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from requests) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from requests) (1.26.6)
Collecting datetime
  Downloading DateTime-4.3-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 8.3 MB/s  eta 0:00:01
Collecting zope.interface
  Downloading zope.interface-5.4.0-cp38-cp38-manylinux2010_x86_64.whl (259 kB)
     |████████████████████████████████| 259 kB 38.0 MB/s eta 0:00:01
Requirement already satisfied: pytz in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from datetime) (2021.1)
Requirement already satisfied: setuptools in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from zope.interface->datetime) (52.0.0.post20211006)
Installing collected packages: zope.interface, datetime
Successfully installed datetime-4.3 zope.interface-5.4.0

## Imports

Import any additional libraries you may need here.

In [2]:
import glob
import pandas as pd
from datetime import datetime

As the exchange rate fluctuates, we will download the same dataset to make marking simpler. This will be in the same format as the dataset you used in the last section

In [3]:
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv

--2021-12-14 06:14:56--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 198.23.119.245
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|198.23.119.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2815 (2.7K) [application/json]
Saving to: ‘bank_market_cap_1.json.1’

bank_market_cap_1.j 100%[===================>]   2.75K  --.-KB/s    in 0s

2021-12-14 06:14:56 (56.9 MB/s) - ‘bank_market_cap_1.json.1’ saved [2815/2815]

--2021-12-14 06:14:57--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 198.23.119.245
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|198.23.119.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1429 (1.4K) [application/json]
Saving to: ‘bank_market_cap_2.json.1’

bank_market_cap_2.j 100%[===================>]   1.40K  --.-KB/s    in 0s

2021-12-14 06:14:57 (24.9 MB/s) - ‘bank_market_cap_2.json.1’ saved [1429/1429]

--2021-12-14 06:14:58--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 198.23.119.245
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|198.23.119.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 590 [text/csv]
Saving to: ‘exchange_rates.csv.1’

exchange_rates.csv. 100%[===================>]     590  --.-KB/s    in 0s

2021-12-14 06:14:59 (14.4 MB/s) - ‘exchange_rates.csv.1’ saved [590/590]

## Extract

### JSON Extract Function

This function will extract JSON files.

In [4]:
def extract_from_json(file_to_process):
    dataframe = pd.read_json(file_to_process)
    return dataframe

## Extract Function

Define the extract function that finds JSON file `bank_market_cap_1.json` and calls the function created above to extract data from them. Store the data in a `pandas` dataframe. Use the following list for the columns.

In [5]:
columns=['Name','Market Cap (US$ Billion)']

In [6]:
def extract():
    columnedDF = pd.DataFrame(columns=columns)
    # Write your code here
    files = glob.glob('*.json', recursive = True)
    print(files)
    df = extract_from_json(files[1])
    print(df)
    columnedDF = columnedDF.append(df)
    print(columnedDF)
    return columnedDF

<b>Question 1</b> Load the file <code>exchange_rates.csv</code> as a dataframe and find the exchange rate for British pounds with the symbol <code>GBP</code>, store it in the variable  <code>exchange_rate</code>, you will be asked for the number. Hint: set the parameter  <code>index_col</code> to 0.

In [7]:
# Write your code here
#extract()
df = pd.read_csv('exchange_rates.csv', index_col = 0)
print(df.loc['GBP']['Rates'])
print(df)
exchange_rate = df.loc['GBP']['Rates']
#print(exchange_rate)

0.7323984208000001
            Rates
AUD      1.297088
BGN      1.608653
BRL      5.409196
CAD      1.271426
CHF      0.886083
CNY      6.483139
CZK     21.510117
DKK      6.119757
EUR      0.822504
GBP      0.732398
HKD      7.752509
HRK      6.222652
HUF    294.135549
IDR  14097.902616
ILS      3.281132
INR     73.011186
ISK    129.133081
JPY    103.791742
KRW   1105.839776
MXN     19.932966
MYR      4.043017
NOK      8.497121
NZD      1.393733
PHP     48.070406
PLN      3.732933
RON      4.008883
RUB     74.930827
SEK      8.292071
SGD      1.328261
THB     30.009870
TRY      7.418572
USD      1.000000
ZAR     15.118441

## Transform

Using <code>exchange_rate</code> and the `exchange_rates.csv` file find the exchange rate of USD to GBP. Write a transform function that

1.  Changes the `Market Cap (US$ Billion)` column from USD to GBP
2.  Rounds the Market Cap (US$ Billion)\` column to 3 decimal places
3.  Rename `Market Cap (US$ Billion)` to `Market Cap (GBP$ Billion)`

In [8]:
def transform(dframe, exchangeRate):
    dframe['Market Cap (US$ Billion)'] = round(dframe['Market Cap (US$ Billion)'] * exchangeRate, 3)
    dframe = dframe.rename(columns={'Market Cap (US$ Billion)': 'Market Cap (GBP$ Billion)'})
    return dframe
    # Write your code here

## Load

Create a function that takes a dataframe and load it to a csv named `bank_market_cap_gbp.csv`. Make sure to set `index` to `False`.

In [9]:
def load(dFrame):
    # Write your code here
    dFrame.to_csv('bank_market_cap_gbp.csv', index=False)

## Logging Function

Write the logging function <code>log</code> to log your data:

In [10]:
def log(message):
    timestamp_format = '%Y-%h-%d-%H:%M:%S' # Year-Monthname-Day-Hour-Minute-Second
    now = datetime.now() # get current timestamp
    timestamp = now.strftime(timestamp_format)
    print(timestamp + ',' + message + '\n')
    with open("logfile.txt","a") as f:
        f.write(timestamp + ',' + message + '\n')
    # Write your code here

## Running the ETL Process

Log the process accordingly using the following <code>"ETL Job Started"</code> and <code>"Extract phase Started"</code>

In [11]:
# Write your code here
log("ETL Job Started")
log("Extract phase Started")

2021-Dec-14-06:14:59,ETL Job Started

2021-Dec-14-06:14:59,Extract phase Started

### Extract

<code>Question 2</code> Use the function <code>extract</code>, and print the first 5 rows, take a screen shot:

In [12]:
# Call the function here
df = extract()


# Print the rows here
print(df.head())

['bank_market_cap_1.json', 'bank_market_cap_2.json']
                                  Name  Market Cap (US$ Billion)
35     Banco Bilbao Vizcaya Argentaria                    60.678
36                     Japan Post Bank                    60.525
37         The Bank of New York Mellon                    59.823
38    Shanghai Pudong Development Bank                    58.796
39             Industrial Bank (China)                    57.388
40           Bank of China (Hong Kong)                    55.449
41                    Bank of Montreal                    53.181
42                     Crédit Agricole                    52.141
43                            DBS Bank                    51.475
44                              Nordea                    51.185
45                         Capital One                    51.107
46                       NatWest Group                    50.490
47              Mizuho Financial Group                    50.018
48                       Credit Suisse                    48.462
49        Postal Savings Bank of China                    47.948
50                 China Minsheng Bank                    47.921
51                           UniCredit                    47.777
52                    China CITIC Bank                    47.451
53                      Hang Seng Bank                    46.171
54                    Société Générale                    46.051
55                            Barclays                    45.850
56  Canadian Imperial Bank of Commerce                    43.544
57                   Bank Central Asia                    43.344
58                    Truist Financial                    41.923
59        Oversea-Chinese Banking Corp                    41.362
60                 State Bank of India                    40.562
61                        State Street                    39.769
62                       Deutsche Bank                    38.649
63                            KBC Bank                    38.394
64                         Danske Bank                    38.223
65                        Ping An Bank                    37.993
66                  Standard Chartered                    37.319
67                United Overseas Bank                    35.128
68                           QNB Group                    33.560
69                         Bank Rakyat                    33.081
                                  Name  Market Cap (US$ Billion)
35     Banco Bilbao Vizcaya Argentaria                    60.678
36                     Japan Post Bank                    60.525
37         The Bank of New York Mellon                    59.823
38    Shanghai Pudong Development Bank                    58.796
39             Industrial Bank (China)                    57.388
40           Bank of China (Hong Kong)                    55.449
41                    Bank of Montreal                    53.181
42                     Crédit Agricole                    52.141
43                            DBS Bank                    51.475
44                              Nordea                    51.185
45                         Capital One                    51.107
46                       NatWest Group                    50.490
47              Mizuho Financial Group                    50.018
48                       Credit Suisse                    48.462
49        Postal Savings Bank of China                    47.948
50                 China Minsheng Bank                    47.921
51                           UniCredit                    47.777
52                    China CITIC Bank                    47.451
53                      Hang Seng Bank                    46.171
54                    Société Générale                    46.051
55                            Barclays                    45.850
56  Canadian Imperial Bank of Commerce                    43.544
57                   Bank Central Asia                    43.344
58                    Truist Financial                    41.923
59        Oversea-Chinese Banking Corp                    41.362
60                 State Bank of India                    40.562
61                        State Street                    39.769
62                       Deutsche Bank                    38.649
63                            KBC Bank                    38.394
64                         Danske Bank                    38.223
65                        Ping An Bank                    37.993
66                  Standard Chartered                    37.319
67                United Overseas Bank                    35.128
68                           QNB Group                    33.560
69                         Bank Rakyat                    33.081
                                Name  Market Cap (US$ Billion)
35   Banco Bilbao Vizcaya Argentaria                    60.678
36                   Japan Post Bank                    60.525
37       The Bank of New York Mellon                    59.823
38  Shanghai Pudong Development Bank                    58.796
39           Industrial Bank (China)                    57.388

Log the data as <code>"Extract phase Ended"</code>

In [13]:
# Write your code here
log("Extract phase Ended")

2021-Dec-14-06:14:59,Extract phase Ended

### Transform

Log the following  <code>"Transform phase Started"</code>

In [14]:
# Write your code here
log("Transform phase Started")

2021-Dec-14-06:14:59,Transform phase Started

<code>Question 3</code> Use the function <code>transform</code> and print the first 5 rows of the output, take a screen shot:

In [15]:
# Call the function here
df = transform(df, exchange_rate)

# Print the first 5 rows here
print(df.head())

                                Name  Market Cap (GBP$ Billion)
35   Banco Bilbao Vizcaya Argentaria                     44.440
36                   Japan Post Bank                     44.328
37       The Bank of New York Mellon                     43.814
38  Shanghai Pudong Development Bank                     43.062
39           Industrial Bank (China)                     42.031

Log your data <code>"Transform phase Ended"</code>

In [16]:
# Write your code here
log("Transform phase Ended")

2021-Dec-14-06:14:59,Transform phase Ended

### Load

Log the following `"Load phase Started"`.

In [17]:
# Write your code here
log("Load phase Started")

2021-Dec-14-06:14:59,Load phase Started

Call the load function

In [18]:
# Write your code here
load(df)

Log the following `"Load phase Ended"`.

In [19]:
# Write your code here
log("Load phase Ended")

2021-Dec-14-06:14:59,Load phase Ended

## Authors

Ramesh Sannareddy, Joseph Santrcangelo and Azim Hirjani

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-11-25        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).